name: Publish to GCR and GHCR

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: "node-app"

jobs:
  build-pipeline-docker:
    name: Build, push, scan, and sign Docker image
    permissions:
      contents: "write"
      id-token: "write"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        env:
            REGISTRY: ghcr.io
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }} 
            password: ${{ secrets.CR_PAT }}

      - name: Login to GCR
        env:
          PROJECT_ID: ${{ vars.PROJECT_ID }}
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          PROJECT_ID: ${{ env.PROJECT_ID }}
        run: docker build --label "org.opencontainers.image.source=https://github.com/gatsbyz/node-app" -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run:  |-
          gcloud auth configure-docker --quiet #authenticate to gcr
        
      - name: Push Docker Image to Container Registry GCR
        env: 
          REGISTRY: gcr.io
          PROJECT_ID: ${{ vars.PROJECT_ID }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |-
          docker tag $IMAGE_NAME:latest $REGISTRY/$PROJECT_ID/$IMAGE_NAME:latest 
          docker push $REGISTRY/$PROJECT_ID/$IMAGE_NAME:latest 
          
      - name: Extract metadata (tags, labels) for Docker GHCR
        env:
          REGISTRY: ghcr.io
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
